from pyspark.sql.types import (
    DecimalType,
    DoubleType,
    IntegerType,
    LongType,
    StringType,
    StructField,
    StructType,
)

# Schema bảng cha (RAW_QTTG_BHXH) 
MASTER_SCHEMA = StructType(
    [
        StructField("ID", LongType(), True),
        StructField("NLD_ID", LongType(), True),
        StructField("SO_SO_BHXH", StringType(), True),
        StructField("THANG_BD", StringType(), True),
        StructField("THANG_KT", StringType(), True),
        StructField("TT_TG_BHXH", StringType(), True),
        StructField("DT_TG_BHXH", StringType(), True),
        StructField("NAM_TG_BHXH", IntegerType(), True),
        StructField("THANG_TG_BHXH", IntegerType(), True),
        StructField("NAM_TG_BHXH_BB", IntegerType(), True),
        StructField("THANG_TG_BHXH_BB", IntegerType(), True),
        StructField("TT_TG_BHTN", StringType(), True),
        StructField("DT_TG_BHTN", StringType(), True),
        StructField("NAM_TG_BHTN", IntegerType(), True),
        StructField("THANG_TG_BHTN", IntegerType(), True),
        StructField("TT_TG_BHYT", StringType(), True),
        StructField("DT_TG_BHYT", StringType(), True),
        StructField("NAM_TG_BHYT", IntegerType(), True),
        StructField("THANG_TG_BHYT", IntegerType(), True),
        StructField("NAM_NO_BHXH", IntegerType(), True),
        StructField("THANG_NO_BHXH", IntegerType(), True),
        StructField("NAM_NO_BHTN", IntegerType(), True),
        StructField("THANG_NO_BHTN", IntegerType(), True),
        StructField("TT_TG_BH", StringType(), True),
        StructField("DT_TG_BH", StringType(), True),
        StructField("TU_THANG_DVI", StringType(), True),
        StructField("DEN_THANG_DVI", StringType(), True),
        StructField("DEN_THANG_HTTT", StringType(), True),
        StructField("DEN_THANG_BHTN", StringType(), True),
        StructField("THANG_BD_LT", StringType(), True),
        StructField("THANG_KT_LT", StringType(), True),
        StructField("SO_THANG_LT", IntegerType(), True),
        StructField("IS_ERRORS", IntegerType(), True),
        StructField("NGHI_VIEC", IntegerType(), True),
        StructField("IS_CONTINUE", IntegerType(), True),
        StructField("TRUY_DONG", IntegerType(), True),
        StructField("DEN_NGAY", StringType(), True),
        StructField("MA_CD", StringType(), True),
        StructField("MA_NHH", StringType(), True),
        StructField("DD_MA_DON_VI", StringType(), True),
        StructField("DD_THANG_DONG_DEN_XH", StringType(), True),
        StructField("DD_TY_LE_NO_BHXH", DecimalType(10, 4), True),
        StructField("DD_THANG_DONG_DEN_YT", StringType(), True),
        StructField("DD_TY_LE_NO_BHYT", DecimalType(10, 4), True),
        StructField("DD_THANG_DONG_DEN_TN", StringType(), True),
        StructField("DD_TY_LE_NO_BHTN", DecimalType(10, 4), True),
        StructField("DD_THANG_DONG_DEN_TNLD", StringType(), True),
        StructField("DD_TY_LE_NO_TNLD", DecimalType(10, 4), True),
        StructField("RAW_RESPONSE", StringType(), True),
        StructField("CREATED_AT", StringType(), True),
    ]
)

# Schema bảng detail (RAW_QTTG_BHXH_DETAIL)
DETAIL_SCHEMA = StructType(
    [
        StructField("ID", LongType(), True),
        StructField("MASTER_ID", LongType(), True),
        StructField("NLD_ID", LongType(), True),
        StructField("DOT_PHAT_SINH", StringType(), True),
        StructField("TU_THANG", StringType(), True),
        StructField("DEN_THANG", StringType(), True),
        StructField("MA_DON_VI", StringType(), True),
        StructField("TEN_DON_VI", StringType(), True),
        StructField("LOAI_DT", StringType(), True),
        StructField("LOAI", IntegerType(), True),
        StructField("PA", StringType(), True),
        StructField("DON_VI_TINH", StringType(), True),
        StructField("MA_NT", StringType(), True),
        StructField("CHUC_DANH_CV", StringType(), True),
        StructField("CHUC_DANH_CV_PRE", StringType(), True),
        StructField("NOI_LAM_VIEC", StringType(), True),
        StructField("NOI_DUNG", StringType(), True),
        StructField("MUC_LUONG", DecimalType(19, 4), True),
        StructField("MUC_LUONG_TN", DecimalType(19, 4), True),
        StructField("MUC_LUONG_BHYT", DecimalType(19, 4), True),
        StructField("MUC_LUONG_PC", DecimalType(19, 4), True),
        StructField("MUC_LUONG_BS", DecimalType(19, 4), True),
        StructField("MUC_LUONG_NLD", DecimalType(19, 4), True),
        StructField("MUC_LUONG_NSNN", DecimalType(19, 4), True),
        StructField("MUC_LUONG_HS", DecimalType(19, 4), True),
        StructField("MUC_LUONG_TT", DecimalType(19, 4), True),
        StructField("HS_LUONG", DecimalType(10, 4), True),
        StructField("PC_CHUC_VU", DecimalType(10, 4), True),
        StructField("PC_THAM_NIEN", DecimalType(10, 4), True),
        StructField("PC_NGHE", DecimalType(10, 4), True),
        StructField("PC_KHU_VUC", DecimalType(10, 4), True),
        StructField("PC_KHAC", DecimalType(10, 4), True),
        StructField("PC_TAI_CU", DecimalType(10, 4), True),
        StructField("HS_TN", DecimalType(10, 4), True),
        StructField("HS_NG", DecimalType(10, 4), True),
        StructField("HS_TC", DecimalType(10, 4), True),
        StructField("TYLE_BHXH", DecimalType(10, 4), True),
        StructField("TYLE_BHYT", DecimalType(10, 4), True),
        StructField("TYLE_BHTN", DecimalType(10, 4), True),
        StructField("TYLE_TUDV", DecimalType(10, 4), True),
        StructField("TYLE_HTTT", DecimalType(10, 4), True),
        StructField("TYLE_ODTS", DecimalType(10, 4), True),
        StructField("TYLE_TNLD", DecimalType(10, 4), True),
        StructField("TYLE_NSNN", DecimalType(10, 4), True),
        StructField("DK1", IntegerType(), True),
        StructField("DK2", IntegerType(), True),
        StructField("DK3", IntegerType(), True),
        StructField("DK4", IntegerType(), True),
        StructField("DK5", IntegerType(), True),
        StructField("DK6", IntegerType(), True),
        StructField("IS_BHXH", IntegerType(), True),
        StructField("IS_BHXH_BB", IntegerType(), True),
        StructField("IS_BHTN", IntegerType(), True),
        StructField("IS_BHYT", IntegerType(), True),
        StructField("IS_BHXH2", IntegerType(), True),
        StructField("IS_BHTN2", IntegerType(), True),
        StructField("IS_ERROR", IntegerType(), True),
        StructField("IS_TR", IntegerType(), True),
        StructField("IS_BONUS", IntegerType(), True),
        StructField("ML_TC", IntegerType(), True),
        StructField("GHI_CHU", StringType(), True),
        StructField("KIEM_TRA", IntegerType(), True),
        StructField("SO_THANG", IntegerType(), True),
        StructField("MA_KHOI_TK", StringType(), True),
        StructField("TY_LE_DONG", DecimalType(10, 4), True),
        StructField("MUC_DONG", DecimalType(19, 4), True),
        StructField("LUONG_CHINH", DecimalType(19, 4), True),
        StructField("CHUC_DANH_NLV", StringType(), True),
        StructField("PHUONG_THUC", StringType(), True),
        StructField("PHUONG_THUC_DONG", StringType(), True),
        StructField("MUC_LUONG_PRE", DecimalType(19, 4), True),
        StructField("MUC_LUONG_PC_PRE", DecimalType(19, 4), True),
        StructField("MUC_LUONG_BS_PRE", DecimalType(19, 4), True),
        StructField("HS_LUONG_PRE", DecimalType(10, 4), True),
        StructField("PC_CHUC_VU_PRE", DecimalType(10, 4), True),
        StructField("PC_THAM_NIEN_PRE", DecimalType(10, 4), True),
        StructField("PC_NGHE_PRE", DecimalType(10, 4), True),
        StructField("PC_KHU_VUC_PRE", DecimalType(10, 4), True),
        StructField("PC_KHAC_PRE", DecimalType(10, 4), True),
        StructField("PC_TAI_CU_PRE", DecimalType(10, 4), True),
        StructField("LUONG_CHINH_PRE", DecimalType(19, 4), True),
        StructField("CREATED_AT", StringType(), True),
    ]
)